### ISSUE TITLE
Binding NumPy's ndarray

### ISSUE THREAD

**Issue by teknikal-wizard** [fable-compiler/Fable.Python#70]
I'm attempting to bind some of the TensorFlow api. Many functions use [ndarray](https://numpy.org/doc/stable/reference/arrays.ndarray.html) from NumPy. Because this in turn [implements the Python array API](https://numpy.org/doc/stable/reference/array_api.html), if you type-alias them as normal arrays in the binding then the F# Array module functions all work fine.

```fsharp
type INDArray<'a> = 'a array
```

The issue I am facing is that ndarray also has instance members that are not part of the basic array type - things like [reshape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html). However, I can't add augmentations to a type alias and you can't inherit from the base collection types

I tried extending the Seq interface but Fable didn't like it when I tried to compile to Python

```fsharp
type INDArray<'a> =
    inherit seq<'a> 
    abstract member reshape : int * int -> INDArray<'a>
```

```bash
Parsing Fable 4 Python Example.fsx...
   at Fable.Transforms.Fable2Python.Util.transformInterface(IPythonCompiler com, Context ctx, Entity classEnt, ClassDecl classDecl) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Python\Fable2Python.fs:line 3776
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons) in /home/dev/Projects/fsharp/src/FSharp.Core/local.fs:line 434
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list) in /home/dev/Projects/fsharp/src/FSharp.Core/local.fs:line 442
   at Fable.Transforms.Fable2Python.Compiler.transformFile(Compiler com, File file) in C:\Users\alfon\repos\Fable\src\Fable.Transforms\Python\Fable2Python.fs:line 4073
   at Fable.Cli.Pipeline.Python.compileFile@237-7.Invoke(Unit unitVar) in C:\Users\alfon\repos\Fable\src\Fable.Cli\Pipeline.fs:line 237
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /home/dev/Projects/fsharp/src/FSharp.Core/async.fs:line 112
Compilation failed
```

I just wondered if anyone else has faced this and already come up with a good solution!

Thanks :)

**Comment by teknikal-wizard** [comment]
I guess I could create an NDArray module with functions for pipelining instead of trying to add instance members.

**Comment by teknikal-wizard** [comment]
I tried 
```fsharp
type INDArray<'a> = 'a array

module NDArray =
    [<Emit("$2.reshape($0, $1)")>]
    let reshape<'a> : int -> int -> INDArray<'a> -> INDArray<'a> = jsNative

image_train |> NDArray.reshape<INDArray<INDArray<uint8>>> 60000 784
```
but this compiled to
```python
(None.reshape(None, None))(60000)(784)(image_train)
```

**Comment by teknikal-wizard** [comment]
This is the repo I am working in if it is useful :)
https://github.com/CompositionalIT/Python-TensorFlow-binding-example

**Comment by dbrattli** [comment]
Thanks for the adding the issue. That compile error is a bug that should be fixed with https://github.com/fable-compiler/Fable/pull/3160 

For the module functions try:

```fs
module NDArray =
    [<Emit("$2.reshape($0, $1)")>]
    let reshape<'a> (a: int) (b: int) (arr: INDArray<'a>) : INDArray<'a> = nativeOnly
```

**Comment by dbrattli** [comment]
(sorry didn't mean to auto-close)

**Comment by teknikal-wizard** [comment]
Awesome, thanks Dag!

**Comment by dbrattli** [comment]
For issues like this it's btw nice to try the code in the [Fable Repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYCh2klAYgQwCMAbMAOgGFgAnMTdJOcKASQDkARAQWuvzgA8AcnwA+KAF50UGVACWEABZhqcpFARgAjsLFRpsosj4BjdajSEVUWgkX5mALnkR1AKhfqAtOPbde-Lqi9KTqKMgAFPgBcM5+PHyCCkiiAJSSBjIRqUA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q). That way you can quickly check if e.g the code works for JS but not for Python. If it works with JS but not with Python then it's most likely a bug in `Fable2Python.fs`. If it also fails for JS then it's most likely a limitation of Fable.

**Comment by teknikal-wizard** [comment]
That's a great idea, I shall do so, thanks :)
